// 每个思维模型的「钩子标题」：一句吸引人的痛点 / 能解决的问题，
// 放在知识卡片封面最上方，让刷到的人一眼被戳中。
// 由 slug 索引，详情页优先读取 model.hook，否则回退到此映射。

export const modelHooks: Record<string, string> = {
  "first-principles": "面对行业报价和老惯例，你敢问一句「为什么只能这样」吗？",
  "second-order-thinking": "做决定只看眼前一步，却被后续的连锁反应反复反噬？",
  "inversion": "正面死磕难题毫无头绪，却从没想过「先避开怎样会失败」？",
  "compound-effect": "努力总是三分钟热度，始终等不到积累带来的那次质变？",
  "feynman-technique": "学了一大堆却讲不明白，其实你根本还没真懂？",
  "pareto-principle": "忙得团团转，却分不清是哪 20% 真正在产出成果？",
  "pyramid-principle": "汇报啰嗦被老板打断，重点总是埋在一堆细节里？",
  "circle-of-competence": "哪热往哪凑，却总在自己看不懂的地方栽跟头？",
  "flywheel-effect": "启动新项目总半途而废，等不到它自己转起来的那一刻？",
  "dunning-kruger": "刚上手觉得「不过如此」，真干起来才知有多难？",
  "eisenhower-matrix": "大事小事混成一团，重要的事总被紧急的挤到一边？",
  "swot-analysis": "做规划全凭感觉，却说不清自己的优势劣势到底在哪？",
  "confirmation-bias": "只信符合自己观点的信息，悄悄错过了关键的反例？",
  "feedback-loop": "反复掉进同一个坑，却找不到那个循环真正的源头？",
  "bayesian-thinking": "一条「阳性」结果就慌了，不会用新证据更新判断？",
  "scqa-model": "写方案开头就堆背景，读者三行不到就关掉了？",
  "deliberate-practice": "练了很久却没长进，原来一直在舒适区里重复？",
  "ten-ten-ten-rule": "为小事纠结半宿，却从不为十年后的自己多做打算？",
  "analogy-thinking": "讲复杂概念像对牛弹琴，对方全程一脸懵？",
  "prisoners-dilemma": "明明合作对双方都好，却被迫和对手互相伤害？",
  "conjunction-fallacy": "被「细节很全」的故事忽悠，忘了它其实更不可能？",
  "middle-state-relaxation": "计划执行到一半就松懈，最后功亏一篑？",
  "sales-funnel": "流量不少转化却惨淡，不知道用户在哪一步溜走？",
  "maslow-hierarchy": "用钱激励员工越来越没用，不懂他卡在更底层的需求？",
  "five-times-communication": "一句话传了几道就变味，执行南辕而北辙？",
  "redundancy-backup": "关键系统毫无备份，一次故障就全盘皆输？",
  "safety-margin": "把账算到刚好够，一点波动就直接爆仓？",
  "pest-analysis": "只盯行业内部，忽略了政策和社会大环境的转向？",
  "boston-matrix": "资源平均撒给所有产品，该砍的没砍、该养的没养？",
  "golden-circle": "产品卖点讲了一堆，用户却不懂你究竟为何而做？",
  "six-thinking-hats": "开会要么吵成一团要么一言堂，缺一套系统视角？",
  "path-dependence": "明知老路不对，却被过去的投入绑着走不下去？",
  "smart-principle": "目标喊得震天响，月底一算全是模糊的「尽量」？",
  "pdca-cycle": "项目做完就散，同样的错下一轮又原样犯一遍？",
  "mece-principle": "分类总有重叠和遗漏，分析怎么都清不干净？",
  "issue-tree": "面对大问题无从下手，东一榔头西一棒槌？",
  "occams-razor": "解释越加越多，却忘了最简单那个可能最对？",
  "johari-window": "团队互相猜忌，谁也不知彼此的真实想法与盲区？",
  "grow-model": "带人只会下指令，对方始终长不出独立解决问题的能力？",
  "five-w-one-h": "方案想到哪说到哪，漏了执行者或期限这种关键要素？",
  "fogg-behavior": "立了无数 flag，却总在「没状态」的那一刻放弃？",
  "spiral-of-silence": "明明不认同，却因为没人发声而不敢开口？",
  "aisas-model": "砸钱投曝光，用户却在搜索环节被竞品截走？",
  "kahneman-dual-system": "冲动决策后又后悔，总被直觉系统带偏？",
  "flow-state": "工作被切得断断续续，深度专注成了奢侈品？",
  "hook-model": "做产品留不住人，不知道到底靠什么让用户回来？",
  "peak-end-rule": "体验做了不少，用户只记得最糟和最后那一刻？",
  "primacy-recency": "讲了半天，对方只记住了开头和结尾两句？",
  "moat-theory": "生意看着红火，却没一样别人抢不走的壁垒？",
  "metacognition": "总在同一类错误里打转，从没跳出来看自己怎么想？",
  "yerkes-dodson": "压力太大就崩、太小又懒散，状态总是调不对？",
  "mvp": "想一口气做完美，结果迟迟不敢上线错过窗口？",
  "long-tail-effect": "只盯爆款，忽视了海量小众需求聚起的利润？",
  "barrel-principle": "团队卡在一个短板上，整条业务线被拖垮？",
  "sunk-cost": "烂项目舍不得停，越投越亏只为「已经花了」？",
  "opportunity-cost": "选了 A 才发现 B 更好，却从没算过放弃的代价？",
  "matthew-effect": "起步只落后一点，越往后差距被越拉越大？",
  "murphys-law": "平时从不出错，一到关键演示现场必出幺蛾子？",
  "parkinsons-law": "任务给一周拖一周，给一天反而一天就搞定？",
  "peter-principle": "把能手一路提拔，最后搁在干不好的位置上？",
  "framing-effect": "同一件事换种说法，对方态度天差地别却不知为何？",
  "prospect-theory": "该赌时怂、该收时贪，被得失的框架死死套住？",
  "mental-accounting": "大钱省着花、零钱瞎挥霍，其实都是同一种钱？",
  "growth-mindset": "一遇挫折就给自己贴「我不行」的标签？",
  "brainstorming": "一开会就互相挑刺，好点子还没冒头就被掐死？",
  "osborn-checklist": "想创新却只会空想，找不到可拆解发力的点？",
  "woop-method": "目标定得漂亮，真到阻力面前轻易就缩回去了？",
  "prep-method": "发言没逻辑，观点抛出去没人信服？",
  "ogsm": "战略写满 PPT，落到执行却没人知道下个月干啥？",
  "attraction-law": "想成为某种人却总被环境带偏，圈子塑造不了结果？",
  "zeigarnik-effect": "开了无数头却收不了尾，未完成的任务在脑里转？",
  "weber-fechner": "调价一点点用户没感觉，调太多又吓跑人？",
  "overview-effect": "陷在琐事里焦虑，看不见自己在全局中的位置？",
  "kiss-review": "方案越搞越复杂，忘了「简单才能跑得通」？",
  "grai-review": "复盘只谈「做了啥」，不连战略到执行的全链路？",
  "nlp-levels": "改变总卡在行为层，没动更底层的身份与信念？",
  "mandala-thinking": "想出一个点子就止步，扩不出八个方向的关联？",
  "3c-model": "创业计划被投资人问住，答不出用户为何选你而非对手？",
  "seci-model": "公司知识全在老人脑子里，人一走经验全带走？",
  "addie-model": "直接做 PPT 就开讲，培训学员听完一头雾水？",
  "ffc-praise": "想夸人却只说「你真棒」，对方听不出真心？",
  "sqrrr-reading": "书读得快忘得也快，读完说不出到底学了啥？",
  "porter-five-forces": "看对手只看直接竞品，忽略上下游和替代品的威胁？",
  "reverse-thinking": "正面推不动，却没试着从结果倒着往回推？",
  "course-separation": "总为别人的情绪买单，分不清谁的事该谁负责？",
  "iceberg-model": "只看表面行为，看不到能力、价值观等底层动因？",
  "fab-method": "卖东西只会堆参数，讲不清对用户到底有啥好处？",
  "stp-model": "产品想讨好所有人，结果谁都没被打动？",
  "rice-method": "需求排期靠拍脑袋，分不清哪个更该先做？",
  "double-target-list": "什么都想抓，到头来重要和紧急全混成一团？",
  "simple-is-best": "东西越加越多，反而把核心价值给淹没了？",
};

export function getModelHook(slug: string, fallback?: string): string {
  return modelHooks[slug] ?? fallback ?? "";
}
